version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/data:/app/app/data
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
